#!/bin/bash

used=$(nvidia-smi --query-gpu=memory.used --format=csv,noheader,nounits)
total=$(nvidia-smi --query-gpu=memory.total --format=csv,noheader,nounits)

if ! [[ $used =~ ^[0-9]+$ ]]; then
  exit 1
fi

div=$(echo "scale=2; $used/$total" | bc)
perc=$(echo "scale=2; ($used/$total)*100" | bc)

echo "VRAM: $used/$total (${perc%.*}%)"
